service: sitemap-products-test

frameworkVersion: '3'
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  memorySize: 128
  timeout: 30
  environment:
    NODE_OPTIONS: '--enable-source-maps'
    DEBUG_CTP_API_URL: ${env:CTP_API_URL}
    CTP_AUTH_URL: ${env:CTP_AUTH_URL}
    CTP_CLIENT_ID: ${env:CTP_CLIENT_ID}
    CTP_CLIENT_SECRET: ${env:CTP_CLIENT_SECRET}
    CTP_PROJECT_KEY: ${env:CTP_PROJECT_KEY}
    CTP_SCOPES: ${env:CTP_SCOPES}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
          Resource: arn:aws:s3:::${self:custom.bucketName}/*

custom:
  bucketName: satya-practise-bucket
  dotenv:
    path: .env

functions:
  createXml:
    handler: index.handler
    description: 'Lambda function to create XML files in S3'
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
          enabled: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
